name: persist-workspace
description: 'A action to persist your workspace across different jobs'
author: bissolli
branding:
  icon: 'box'  
  color: 'green'
inputs:
  action:
    required: false
    options:
      - retrieve
      - persist
  artifactName:
    required: false

    
runs:
  using: "composite"
  steps:
    - name: Create the workspace artifact
      if: ${{ inputs.action != 'retrieve' }}
      shell: bash
      run: tar -cf workspace.tar --exclude=workspace.tar .
    - name: Upload the workspace artifact
      if: ${{ inputs.action == 'persist' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifactName || 'persisted-artifact' }}
        path: workspace.tar
        if-no-files-found: error
    - name: Retrieve workspace
      if: ${{ inputs.action == 'retrieve' }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifactName || 'persisted-artifact' }}
    - name: Extract workspace
      if: ${{ inputs.action == 'retrieve' }}
      shell: bash
      run: |
        ls -lah
        tar -xf workspace.tar